name: Update Recent Activity on Profile

on:
  schedule:
    # Каждый час обновлять раздел Recent Activity на профиле
    - cron: "0/30 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Recent Activity on Profile
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: dima-dmytruk23
          COMMIT_MSG: "Update Recent Activity on Profile"
          MAX_LINES: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
